baseURL = "https://www.chathandriehuys.com"
languageCode = 'en-us'
title = 'Chathan Driehuys - Software Developer'

summaryLength = 50

[markup.goldmark.renderer]
  unsafe = true

[params]
  dateFormat = "2006-01-02"
