[build]
  publish = "public"
  command = "npm run build"

  [build.environment]
    HUGO_VERSION = "0.122.0"
    HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build -- -- --baseURL $DEPLOY_PRIME_URL"
